#!yaml
name: Push to Docker registry
#https://blog.shin1x1.com/entry/docker-multi-arch-build-on-github-actions
on:
  schedule:
    - cron: '0 8 */3 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kansaipg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo ${{github.ref_name}}

      - name: Build latest and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./latest/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kansaipg/docker-coc.nvim:latest

      - name: Build jedi-language-server and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./python-jedi-phpls/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kansaipg/docker-coc.nvim:python-jedi-php
