#!yaml
name: Push to Docker registry
#https://blog.shin1x1.com/entry/docker-multi-arch-build-on-github-actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kansaipg
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build -t kansaipg/docker-coc.nvim:latest -f ./latest/Dockerfile .
          docker build -t kansaipg/docker-coc.nvim:python-jedi-php -f ./python-jedi-phpls/Dockerfile .
          
          
      - name: Build Docker Image
        run: |
          docker push kansaipg/docker-coc.nvim:latest
          docker push kansaipg/docker-coc.nvim:python-jedi-php
          
#       - name: Build latest and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./latest/Dockerfile
#           platforms: linux/amd64
#           push: true
#           tags: kansaipg/docker-coc.nvim:latest

#       - name: Build jedi-language-server and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./python-jedi-phpls/Dockerfile
#           platforms: linux/amd64
#           push: true
#           tags: kansaipg/docker-coc.nvim:python-jedi-php
