#!yaml
name: Push to Docker registry
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kansaipg
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build -t kansaipg/docker-coc.nvim:latest -f ./latest/Dockerfile ./latest/
          docker build -t kansaipg/docker-coc.nvim:python-jedi-php -f ./python-jedi-phpls/Dockerfile ./python-jedi-phpls/
          
          
      - name: push Docker Image
        run: |
          docker push kansaipg/docker-coc.nvim:latest
          docker push kansaipg/docker-coc.nvim:python-jedi-php
