#!yaml
name: Push to Docker registry
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login
        run: | 
          docker login ghcr.io -u kansai-pg -p ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/kansai-pg/docker-coc.nvim:latest -f ./latest/Dockerfile ./latest/
          docker build -t ghcr.io/kansai-pg/docker-coc.nvim:python-jedi-php -f ./python-jedi-phpls/Dockerfile ./python-jedi-phpls/
          
          
      - name: push Docker Image
        run: |
          docker push ghcr.io/kansai-pg/docker-coc.nvim:latest
          docker push ghcr.io/kansai-pg/docker-coc.nvim:python-jedi-php
